restart-times: 0
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
jobs: 1
keep-going: true
reason: true
printshellcmds: true
jobname: "{name}.{jobid}.snakejob.sh"
use-conda: true
conda-prefix: ".snakemake/conda"
