Steps: ["Alignment_countTable_GE","Alignment_countTable_ADT","Alignment_annotations_TCR_BCR","Droplets_QC_GE","Filtering_GE","Norm_DimRed_Eval_GE","Clust_Markers_Annot_GE","Adding_ADT","Adding_TCR","Adding_BCR","Cerebro"]

############################################ GE (RNA) ############################################

Alignment_countTable_GE:
### Project
 sample.name.ge : ["sc5p_v2_hs_PBMC_1k_5gex"]
 input.dir.ge : '/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/fastq_10X/'
 output.dir.ge : '/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/Results/'
 sctech : '10xv2'
 kindex.ge : '/mnt/beegfs/database/bioinfo/single-cell/INDEX/KB-python_KALLISTO/0.24.4_0.46.2/homo_sapiens/GRCh38/Ensembl/r99/cDNA_LINCs_MIRs/GRCH38_r99_cDNA_linc_mir.kidx'
 tr2g.file.ge : '/mnt/beegfs/database/bioinfo/single-cell/INDEX/KB-python_KALLISTO/0.24.4_0.46.2/homo_sapiens/GRCh38/Ensembl/r99/cDNA_LINCs_MIRs/GRCH38_r99_cDNA_linc_mir_tr2gs.txt'
 reference.txt: "Ensembl reference transcriptome v99 corresponding to the homo sapiens GRCH38 build"

Droplets_QC_GE:
 author.name : "marine aglave"
 author.mail : "marine.aglave@gustaveroussy.fr, bigr@gustaveroussy.fr"

Filtering_GE:
 pcmito.max : 0.15

Norm_DimRed_Eval_GE:
 eval.markers : "GAPDH"

Clust_Markers_Annot_GE:
 markfile : "/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/markfile.xlsx"
 keep.dims : 35
 keep.res : 1.2

############################################ ADT ############################################

Alignment_countTable_ADT:
 sample.name.adt : ["sc5p_v2_hs_PBMC_1k_5fb"]
 input.dir.adt : "/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/fastq_10X/"
 output.dir.adt : "/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/Results/"
 kindex.adt : "/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/INDEX_ADT/ADT.kidx"
 tr2g.file.adt : "/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/INDEX_ADT/ADT_tr2gs.txt"

Adding_ADT:
 gene.names: "CD3G,CD19,PTPRC,CD4,CD8A,CD14,FCGR3A,NCAM1,IL2RA,PTPRC,PDCD1,TIGIT,IGHG1,IGHG2,IGHG2,IL7R,FUT4,CCR7,HLA-DRA"

############################################ TCR/BCR ############################################

Alignment_annotations_TCR_BCR:
sample.name.tcr : ["sc5p_v2_hs_PBMC_1k_t"]
input.dir.tcr : "/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/fastq_10X/"
sample.name.bcr : ["sc5p_v2_hs_PBMC_1k_b"]
input.dir.bcr : "/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/fastq_10X/"
output.dir.tcr_bcr : "/mnt/beegfs/userdata/m_aglave/pipeline/single-cell/examples/complete_individual_analysis_example_of_wiki/Results/"
