Steps: ["Alignment_countTable_GE","Alignment_countTable_ADT","Alignment_annotations_TCR_BCR","Droplets_QC_GE","Filtering_GE","Norm_DimRed_Eval_GE","Clust_Markers_Annot_GE","Adding_ADT","Adding_TCR","Adding_BCR","Cerebro"]
Sctech: '10xv2_5p'
Species: "homo_sapiens"
Author.name: "marine aglave"
Author.mail: "marine.aglave@gustaveroussy.fr, bigr@gustaveroussy.fr"

############################################ GE (RNA) ############################################

Alignment_countTable_GE:
  sample.name.ge : ["sc5p_v2_hs_PBMC_1k_5gex"]
  input.dir.ge : "/mnt/beegfs02/pipelines/bigr_single-cell/2.0.0/examples/complete_individual_analysis_example_of_wiki/fastq_10X/"
  output.dir.ge : "/mnt/beegfs02/pipelines/bigr_single-cell/2.0.0/examples/complete_individual_analysis_example_of_wiki/Results_to_remove/"

Filtering_GE:
  pcmito.max : 15

Norm_DimRed_Eval_GE:
  eval.markers : "GAPDH"
#  vtr.biases.norm : ["nCount_RNA", "nCount_RNA,percent_rb"]
#  eval.dims.min : 19
#  eval.dims.max : 19
#  eval.res.max : 3

Clust_Markers_Annot_GE:
  markfile : "/mnt/beegfs02/pipelines/bigr_single-cell/2.0.0/examples/complete_individual_analysis_example_of_wiki/markfile.xlsx"
  keep.dim.res : ["19_0.3","19_1.6"]

############################################ ADT ############################################

Alignment_countTable_ADT:
  sample.name.adt : ["sc5p_v2_hs_PBMC_1k_5fb"]
  input.dir.adt : "/mnt/beegfs02/pipelines/bigr_single-cell/2.0.0/examples/complete_individual_analysis_example_of_wiki/fastq_10X/"
  output.dir.adt : "/mnt/beegfs02/pipelines/bigr_single-cell/2.0.0/examples/complete_individual_analysis_example_of_wiki/Results/"
  features.fa.adt : "/mnt/beegfs02/pipelines/bigr_single-cell/2.0.0/examples/complete_individual_analysis_example_of_wiki/features.fa"

Adding_ADT:
  gene.names : "CD3G,CD19,PTPRC,CD4,CD8A,CD14,FCGR3A,NCAM1,IL2RA,PTPRC,PDCD1,TIGIT,IGHG1,IGHG2,IGHG2,IL7R,FUT4,CCR7,HLA-DRA"

############################################ TCR/BCR ############################################

Alignment_annotations_TCR_BCR:
  sample.name.tcr : ["sc5p_v2_hs_PBMC_1k_t"]
  input.dir.tcr : "/mnt/beegfs02/pipelines/bigr_single-cell/2.0.0/examples/complete_individual_analysis_example_of_wiki/fastq_10X/"
  sample.name.bcr : ["sc5p_v2_hs_PBMC_1k_b"]
  input.dir.bcr : "/mnt/beegfs02/pipelines/bigr_single-cell/2.0.0/examples/complete_individual_analysis_example_of_wiki/fastq_10X/"
  output.dir.tcr_bcr : "/mnt/beegfs02/pipelines/bigr_single-cell/2.0.0/examples/complete_individual_analysis_example_of_wiki/Results/"
