restart-times: 5
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
jobs: 30
keep-going: true
reason: true
printshellcmds: true
jobname: "{name}.{jobid}.snakejob"
use-conda: true
conda-prefix: /mnt/beegfs/userdata/m_aglave/pipeline/scRNAseq_10X/envs/conda
